version: "3.3"
services:
  app:
    build:
      context: ./../../
      dockerfile: example/monitoring/Dockerfile
      target: app
    restart: always
    ports:
      - 8087:8087
      - 8088:8088
