version: "3.3"
services:
  app:
    build:
      context: ./../../
      dockerfile: example/s3/Dockerfile
      target: app
    restart: "no"
    ports:
      - 8088:8088
    networks:
      - app_network
    depends_on:
      localstack:
        condition: service_healthy
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=s3
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      app_network:
        aliases:
          - s3.localhost.localstack.cloud
          - testbucket.s3.localhost.localstack.cloud
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4566"]
        interval: 10s
        timeout: 5s
        retries: 5
networks:
  app_network:
    driver: bridge
